version: "3.7"

services:
  api:
    environment:
      FLASK_DEBUG: 1
      AUTH0_DOMAIN: studio-rubik.auth0.com
      AUTH0_CLIENT_ID: fake-auth0-client-id
      AUTH0_CLIENT_SECRET: fake-auth0-client-secret
      AUTH0_API_AUDIENCE: https://studio-rubik.auth0.com/api/v2/
      FRONTEND_URL: http://127.0.0.1:3000
